---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::Branchcodes
## it defines mappings from yet-unknown Voyager column to Koha's branchcode used in various tables.
##

_DEFAULT_:      main
