---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::CallSlipStatuses
## it defines mappings from voyager.call_slip.status to koha.reserves.found et. al.
##


#voyager.CALL_SLIP_STATUS_TYPE.csv
#STATUS_DESC   action          #STATUS_TYPE
                                      # Personally speculating that the statuses here are in the order they typically flow through.
Accepted:   isWaitingForFulfilment()  #"1"   # Request accepted and can be fulfilled. Possibly in queue to the call slip printer?
                                             ## The requested item is not checked out, not on hold

Printed:    isWaitingForFulfilment()  #"2"   # Request received and printed as a slip. Waiting for a librarian to pick up the slip and get to work.
                                             ## No example found to analyze

Reassigned: whatDoWeDo()              #"3"   # ??
                                             ## No example found to analyze

Filled:     isWaitingForPickup()      #"4"   # Call request fulfilled. If the item is checked in to the patron, call_request-row is satisfied, otherwise should have a matching call_request-row
                                             ## The requested item might be checked out or on hold

Not Filled: isWaitingForFulfilment()  #"5"   # Being processed somewhere, but not abandoned?
                                             ## The requested item is not checked out, not on hold

Expired:    $DELETE                   #"6"   # Expired is no longer relevant
                                             ## No example found to analyze

Cancelled:  $DELETE                   #"7"   # Cancelled don't generate hold-requests.
                                             ## Examples inconsistent

Error:      $DELETE                   #"8"   # Error doesn't generate hold-requests either
                                             ## No example found to analyze

Promoted:   whatDoWeDo()              #"9"   # ??
                                             ## No example found to analyze

_DEFAULT_:  whatDoWeDo()
