---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::FineType
## it defines mappings from voyager.fine_fee.fine_fee_type to koha.accountlines.accounttype
##

# JYU source values

# fine_fee_type,fine_fee_desc
# 1,Overdue
# 2,Lost Item Replacement
# 3,Lost Item Processing
# 4,Media Booking Late Charge
# 5,Media Booking Usage Fee
# 6,Equipment Replacement
# 7,Lost Equipment Processing
# 11,*Saap.ilm.maksu
# 12,*Osoitetiedustelumaksu
# 13,*Lukusalilaina myöh.maksu
# 14,*Kaukol.karh.postitus
# 15,*Ei lunastettu kaukolaina
# 16,*Kaukopalv.lainakielto
# 17,*Poistettu nide
# 18,*Luvaton ain. säil.paik.
# 19,*Laskun käsittelymaksu
# 8,Accrued Fine
# 9,Accrued Demerit
# 10,Demerit
# 20,*Vapaakpl kotilainassa
# 21,*Kirja haettu hyllystä
# 22,Testing
# 23,*Kirjan korjausmaksu


# For values in Koha, see. https://wiki.koha-community.org/wiki/Hard_Coded_Values

1:  O # Overdue
3:  L # Lost item processing
8:  FU # Accured fine
16: F # Kaukopalvelun lainauskielto
17: F # Poistettu nide
19: F # Lasun käsittelymaksu
21: M # Kirja haettu hyllystä

