---

##
## IN THIS FILE
##
## This mapping table is used by the module MMT::TranslationTable::ItemStatistics
## it defines mappings from Voyager.item_stats.item_stat_id types to koha.items.ccode
##

#Voyager.ITEM_STAT_CODE
#ITEM_STAT_ID,          ITEM_STAT_CODE,      #ITEM_STAT_CODE_DESC

f: f # Avohyllyyn
v: v # Avohyllyst채 varastoon
h: h # Hyllyst채 toiseen
p: p # Laitokselta p채채kirjastoon
k: k # Korvaa avohyllyn kirjan 

_DEFAULT_: warning()

